
default: &default
  adapter: mysql2
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: freemarket_sample_0609d_development

test:
  <<: *default
  database: freemarket_sample_0609d_test

production:
  <<: *default
  database: freemarket_sample_0609d_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock
